src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="posts")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $postedAt;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="3")
     */
    private $postHead;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     * @Assert\Length(min="50", max="1000")
     */
    private $postBody;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="post")
     * @ORM\OrderBy({"commentedAt" = "ASC"})
     */
    private $comments;

    public function __construct()
    {
        $this->postedAt = new \DateTime();
        $this->comments = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPostedAt(): ?\DateTimeInterface
    {
        return $this->postedAt;
    }

    public function setPostedAt(\DateTimeInterface $postedAt): self
    {
        $this->postedAt = $postedAt;

        return $this;
    }

    public function getPostHead(): ?string
    {
        return $this->postHead;
    }

    public function setPostHead(string $postHead): self
    {
        $this->postHead = $postHead;

        return $this;
    }

    public function getPostBody(): ?string
    {
        return $this->postBody;
    }

    public function setPostBody(string $postBody): self
    {
        $this->postBody = $postBody;

        return $this;
    }

    public function getShortBodyCheat(): ?string
    {
        if (mb_strlen($this->postBody) <= 255)
        {
            return $this->postBody;
        }

        $short = mb_substr($this->postBody, 0, 255);
        $spacePosition = mb_strrpos($short, ' ');

        if ($spacePosition === false)
        {
            return $short.'...';
        }

        $short = mb_substr($short, 0, $spacePosition);

        return $short.'...';
    }

    public function getShortBody():? string
    {
        $aPosition = mb_strpos($this->postBody, "\n");
        return $short = mb_substr($this->postBody, 0, $aPosition);

    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('postHead')
            ->add('postBody')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Post;
use App\Form\CommentType;
use App\Form\PostType;
use App\Service\Comments;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

class PostController extends AbstractController
{
    /**
     * @Route("/post", name="post")
     */
    public function index(Request $request, EntityManagerInterface $entityManager)
    {
        $post = new Post();

        $form = $this->createForm(PostType::class, $post); //Строим форму используя PostType
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) // Валидируем и записываем в базу данных
        {
            $entityManager->persist($post);
            $entityManager->flush();

            $this->addFlash('success', 'Success!');

            return $this->redirectToRoute('post_show',['id' => $post->getId()]);
        }

        return $this->render('post/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/post/{id}", name="post_show", requirements={"id" = "\d+"})
     * @ParamConverter("post", options={"mapping"={"id"="id"}})
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function show(Post $post, Comments $commentsService,
                         Request $request, EntityManagerInterface $entityManager)
    {
        $newComment = new Comment();

        $newComment->setPost($post);

        $form = $this->createForm(CommentType::class, $newComment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) // Валидируем и записываем в базу данных
        {
            $entityManager->persist($newComment);
            $entityManager->flush();

            return $this->redirectToRoute('post_show',['id' => $post->getId()]);
        }

        return $this->render('post/show.html.twig',[
            'post'=> $post,
            'comments'=>$commentsService->getAll(),
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/post/{id}/edit", name="post_edit", requirements={"id" = "\d+"})
     * @ParamConverter("post", options={"mapping"={"id"="id"}})
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function edit(Request $request, Post $post,
                         EntityManagerInterface $entityManager)
    {

        $form = $this->createForm(PostType::class,$post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) // Валидируем и записываем в базу данных
        {
            $entityManager->persist($post);
            $entityManager->flush();

            $this->addFlash('success', 'Success!');

            return $this->redirectToRoute('post_show',['id' => $post->getId()]);
        }

        return $this->render('post/edit.html.twig', [
            'form' => $form->createView(),
            'post' => $post,
        ]);
    }
}

templates/post/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello!{% endblock %}

{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block body %}



    <div class="example-wrapper">
        <hr>
        <a href="{{ path('homepage') }}"><< Main page</a>
        <hr>
        <h3>Edit post {{ post.postedAt|date("d.m.Y h:m:s A") }}</h3>

        {{ form_start(form, {'attr': {'novalidate':'novalidate'}}) }}

        {{ form_row(form.postHead,{ 'label': 'Subject' }) }}

        {{ form_row(form.postBody,{ 'label': 'Text' }) }}

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello!{% endblock %}

{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block body %}
    <div class="example-wrapper">

        <hr>
        <a href="{{ path('homepage') }}"><< Main page</a>
        <hr>

        <h3>Create new post</h3>

        {{ form_start(form, {'attr': {'novalidate':'novalidate'}}) }}

        {{ form_row(form.postHead,{ 'label': 'Subject' }) }}

        {{ form_row(form.postBody,{ 'label': 'Text' }) }}

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Post</button>
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Symfony Blog{% endblock %}

{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block body %}

    <hr>
    <a href="{{ path('homepage') }}"><< Main page</a>
    <hr>

    <h5 style="font-weight: bold">{{ post.postHead }}</h5>
    <p>{{ post.postedAt|date("d.m.Y h:m:s A") }}</p>
    <p>{{ post.postBody|nl2br }}</p>
    <hr>
    <a href="{{ path('post_edit', {'id': post.id}) }}">Edit</a>
    <hr>

    {% if comments %}
        <div class="row justify-content-end">
             <div class="col-11">
                {% for comment in post.comments %}
                    <h6 style="font-weight: bold">{{ comment.nickname }}</h6>
                    <p>{{ comment.commentedAt|date("d.m.Y h:m:s A") }}</p>
                    <p>{{ comment.commentBody|nl2br }}</p>
                    <hr>
                {% endfor%}
            </div>
        </div>
    {% endif %}

    {{ form_start(form, {'attr': {'novalidate':'novalidate'}}) }}

    {{ form_row(form.nickname,{ 'label': 'Nickname' }) }}

    {{ form_row(form.commentBody,{ 'label': 'Comment' }) }}

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    {{ form_end(form) }}



{% endblock %}

templates/post/showAll.html.twig
{% extends 'base.html.twig' %}

{% block title %}Symfony Blog{% endblock %}

{% block body %}
    <hr>
    <a href="{{ path('homepage') }}"><< Main page</a>
    <hr>
    <h3>History</h3>
    <hr>
    {% for post in posts|reverse %}
        <h5> <a href="{{ path('post_show', {'id': post.id}) }}">{{ post.postHead }}</a></h5>
        <p>{{ post.postedAt|date("d.m.Y h:i:s A") }}</p>
        <p>{{ post.shortBodyCheat|nl2br }}</p>
        <hr>
    {% endfor %}

{% endblock %}